"use client";

import { useState, useCallback } from "react";
import { useDropzone } from "react-dropzone";
import Tesseract from "tesseract.js";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function SolarStudyAutomated() {
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);

  // Constants from your Biskra Memoir
  const P_INSTALLED = 285.13;
  const CAPEX = 24408342;
  const EFF_TARIFF = 4.8018;
  const DEMAND_SAVINGS = 120000;
  const MONTHLY_PROD = [
    28534, 30958, 40218, 41536, 47221, 46487, 47587, 45896, 39322, 36188, 27793,
    26180,
  ];

  const onDrop = useCallback(async (acceptedFiles: File[]) => {
    if (acceptedFiles.length === 0) return;

    setIsProcessing(true);
    const extractedMonthlyData: { hp: number; peak: number }[] = [];

    for (let i = 0; i < acceptedFiles.length; i++) {
      setProgress(Math.round(((i + 1) / acceptedFiles.length) * 100));

      try {
        const {
          data: { text },
        } = await Tesseract.recognize(acceptedFiles[i], "fra+eng");

        // Logic to find numbers near keywords "Cadran" or "Index"
        // This is a basic regex approach for Sonelgaz bills
        const numbers = text.match(/\d+/g)?.map(Number) || [];

        // We assume the two largest numbers found in the bill are the consumption values
        // In a real production app, you'd use more specific coordinate-based OCR
        const sortedNumbers = [...numbers].sort((a, b) => b - a);
        extractedMonthlyData.push({
          hp: sortedNumbers[0] || 0,
          peak: sortedNumbers[1] || 0,
        });
      } catch (err) {
        console.error("Error reading bill:", err);
      }
    }

    generateAutomatedReport(extractedMonthlyData);
    setIsProcessing(false);
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { "image/*": [] },
  });

  const generateAutomatedReport = (data: { hp: number; peak: number }[]) => {
    let totalSelfConsumed = 0;
    let totalDemand = 0;

    data.forEach((m, i) => {
      const monthCons = m.hp + m.peak;
      const monthProd = MONTHLY_PROD[i] || prodAnnual / 12;
      totalSelfConsumed += Math.min(monthProd, monthCons);
      totalDemand += monthCons;
    });

    const prodAnnual = MONTHLY_PROD.reduce((a, b) => a + b, 0);
    const scr = (totalSelfConsumed / prodAnnual) * 100;
    const savings = totalSelfConsumed * EFF_TARIFF + DEMAND_SAVINGS;
    const spp = CAPEX / savings;

    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("Automated Solar Techno-Economic Report", 105, 20, {
      align: "center",
    });
    doc.setFontSize(10);
    doc.text(
      "Generated by Biskra Solar Engine - Professional Analysis",
      105,
      28,
      { align: "center" },
    );

    autoTable(doc, {
      startY: 40,
      head: [["Technical Metric", "Value", "Unit"]],
      body: [
        ["System Capacity", P_INSTALLED, "kWp"],
        ["Est. Annual Production", prodAnnual.toLocaleString(), "kWh/yr"],
        ["Extracted Facility Demand", totalDemand.toLocaleString(), "kWh/yr"],
        ["Actual Self-Consumption (SCR)", `${scr.toFixed(2)}%`, ""],
      ],
    });

    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [["Financial Forecast", "Value", "Notes"]],
      body: [
        ["Initial Investment", `${CAPEX.toLocaleString()} DA`, "CAPEX"],
        [
          "Annual Bill Savings",
          `${savings.toLocaleString()} DA`,
          "At 4.8018 DA/kWh",
        ],
        ["Simple Payback", `${spp.toFixed(1)} Years`, "ROI Period"],
        ["LCOE", "4.92 DA/kWh", "Cost of Solar vs Grid"],
      ],
    });

    doc.save("Solar_Feasibility_Study.pdf");
  };

  return (
    <div className="max-w-3xl mx-auto my-20 p-10 bg-white border border-gray-200 rounded-3xl shadow-2xl">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-black text-gray-900">
          One-Click Solar Study
        </h1>
        <p className="text-gray-500 mt-3">
          Upload your bills. We do the engineering. You get the PDF.
        </p>
      </div>

      <div
        {...getRootProps()}
        className={`relative h-64 border-4 border-dashed rounded-3xl flex flex-col items-center justify-center transition-all cursor-pointer ${
          isDragActive
            ? "border-blue-500 bg-blue-50"
            : "border-gray-200 hover:border-gray-400 bg-gray-50"
        }`}
      >
        <input {...getInputProps()} />

        {isProcessing ? (
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-xl font-bold text-blue-600">
              Analyzing Bills... {progress}%
            </p>
            <p className="text-sm text-gray-400">
              Extracting data using local OCR
            </p>
          </div>
        ) : (
          <div className="text-center">
            <div className="text-6xl mb-4">📄</div>
            <p className="text-lg font-semibold text-gray-700">
              Drop 12 Sonelgaz bills here
            </p>
            <p className="text-sm text-gray-400 mt-1">
              Images are processed privately in your browser
            </p>
          </div>
        )}
      </div>

      <div className="mt-10 flex items-center justify-between text-xs text-gray-400 font-medium uppercase tracking-widest">
        <span>Biskra GHI: 5.5 kWh/m²</span>
        <span>Tariff: HTA 42</span>
        <span>LCOE: 4.92 DA</span>
      </div>
    </div>
  );
}
